[project]
name = "simple-yt-api"
version = "4.1.0"
authors = [
    { name = "Ahmet Burhan Kayalı", email = "ahmetburhan1703@gmail.com" },
]
description = "A simple and easy-to-use unofficial YouTube API Wrapper."
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
license-files = ["LICENSE"]
keywords = [
    "simple",
    "unofficial",
    "youtube",
    "api",
    "metadata",
    "transcript",
    "wrapper",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Internet :: WWW/HTTP",
    "Topic :: Multimedia :: Video",
    "Topic :: Text Processing :: Markup :: HTML",
]

dependencies = [
    "requests>=2.32.5",
    "beautifulsoup4>=4.14.3",
    "youtube-transcript-api>=1.2.4",
    "fake-useragent==2.2.0",
]

[project.urls]
Homepage = "https://github.com/SoAp9035/simple-yt-api"
Repository = "https://github.com/SoAp9035/simple-yt-api"
Issues = "https://github.com/SoAp9035/simple-yt-api/issues"

[build-system]
requires = ["uv_build>=0.11.8,<0.12"]
build-backend = "uv_build"
